name: Build and Release VM Images

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-vm:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        lfs: true
        
    - name: Setup Git LFS
      run: |
        git lfs install
        git lfs pull
        
    - name: Verify VM images
      run: |
        echo "📦 VM Image files:"
        ls -lh *.vhdx.gz || echo "No VHDX files found"
        
        echo "📋 Documentation files:"
        ls -la *.md *.sh
        
    - name: Create checksums
      run: |
        echo "🔒 Creating checksums for VM images..."
        sha256sum *.vhdx.gz > checksums.txt
        cat checksums.txt
        
    - name: Upload VM artifacts
      uses: actions/upload-artifact@v4
      with:
        name: go125-hyperv-vm-images
        path: |
          *.vhdx.gz
          *.md
          *.sh
          checksums.txt
        retention-days: 90
        
    - name: Create Release (if tagged)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          *.vhdx.gz
          *.md
          *.sh  
          checksums.txt
        body: |
          # Go 1.25.1 Development VM for Windows 11 Hyper-V
          
          ## 🚀 Complete Development Environment
          
          ### VM Images
          - `fedora-coreos-go125-hyperv-fixed.vhdx.gz` - **Recommended** (Better performance)
          - `fedora-coreos-go125-hyperv-dynamic.vhdx.gz` - Space efficient
          
          ### What's Included
          ✅ **Go 1.25.1** (latest AMD64)  
          ✅ **Development tools**: make, gcc, git, vim, tmux, htop, tree  
          ✅ **Network utilities**: curl, wget, rsync  
          ✅ **Languages**: Python 3.13.7, Node.js 22.19.0  
          ✅ **Pre-configured environment** with aliases and shortcuts  
          
          ### Installation
          1. Download `fedora-coreos-go125-hyperv-fixed.vhdx.gz`
          2. Decompress: `gunzip *.vhdx.gz`
          3. Import into Hyper-V (Generation 2, disable Secure Boot)
          4. First boot: `./setup-complete-dev-environment.sh`
          5. Reboot and start developing!
          
          ### Verification
          ```bash
          sha256sum -c checksums.txt
          ```
          
          **Ready for Go 1.25.1 development on Windows 11!** 🎯
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Notify completion
      run: |
        echo "✅ VM images processed successfully!"
        echo "📦 Artifacts uploaded for ${{ github.sha }}"
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          echo "🚀 Release created for tag: ${GITHUB_REF#refs/tags/}"
        fi

  verify-vm:
    runs-on: ubuntu-latest
    needs: build-vm
    
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: go125-hyperv-vm-images
        
    - name: Verify artifacts
      run: |
        echo "📋 Downloaded artifacts:"
        ls -la
        
        echo "🔒 Verifying checksums:"
        sha256sum -c checksums.txt
        
        echo "📊 VM image sizes:"
        ls -lh *.vhdx.gz
        
        echo "✅ All artifacts verified successfully!"
